### ISSUE TITLE
java.lang.Error: unrecognized cert hash

### ISSUE THREAD

**Issue by imperialc0der** [httptoolkit/android-ssl-pinning-demo#3]
Hey there, while trying ssl pinning bypass on the demo app, whenever i click "Manually pinned Request", it only gives me an error which goes by "java.lang.Error: unrecognized cert hash". There's nothing wrong with my burp certificate. (All the other buttons work just fine) 

Emulator - Waydroid
Android Version - 11

![image](https://github.com/httptoolkit/android-ssl-pinning-demo/assets/114372455/b4dee165-6dbe-4391-beff-29611768fc1c)

**Comment by pimterry** [comment]
Yes - that's expected. That means your SSL pinning bypass doesn't handle this case, which makes sense if you're using any "off the shelf" unpinning tool, because it's manually pinned, i.e. it uses custom logic in the app that checks this certificate.

This is a general issue: no ssl unpinning solution can automatically disable _all_ pinning, they can only disable pinning in situations they recognize, so custom solutions like this will always require reverse engineering. There's a guide on how to solve this (in general, but using this app as an example) here: https://httptoolkit.com/blog/android-reverse-engineering/
